//
// Created by ASUS on 2026/5/15.
//

#ifndef BILLANDSALE_SYSTEM_INVENTORY_CONTROLLOR_H
#define BILLANDSALE_SYSTEM_INVENTORY_CONTROLLOR_H


class inventory_controllor {
};


#endif //BILLANDSALE_SYSTEM_INVENTORY_CONTROLLOR_H