//
// Created by ASUS on 2026/5/15.
//

#ifndef BILLANDSALE_SYSTEM_BALANCE_CONTROLLOR_H
#define BILLANDSALE_SYSTEM_BALANCE_CONTROLLOR_H


class balance_controllor {
};


#endif //BILLANDSALE_SYSTEM_BALANCE_CONTROLLOR_H